"""model Admin add blog_title,blog_sub_title,about

Revision ID: 7f8a402504b8
Revises: 
Create Date: 2018-10-15 15:37:53.719975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8a402504b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('about', sa.TEXT(), nullable=True))
    op.add_column('admin', sa.Column('blog_sub_title', sa.String(length=100), nullable=True))
    op.add_column('admin', sa.Column('blog_title', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'blog_title')
    op.drop_column('admin', 'blog_sub_title')
    op.drop_column('admin', 'about')
    # ### end Alembic commands ###
